
# This file was generated by the Tkinter Designer by Parth Jadhav
# https://github.com/ParthJadhav/Tkinter-Designer


from pathlib import Path

# from tkinter import *
# Explicit imports to satisfy Flake8
from tkinter import Tk, Canvas, Entry, Text, Button, PhotoImage

OUTPUT_PATH = Path(__file__).parent
ASSETS_PATH = OUTPUT_PATH / Path(r"C:\Users\rocr2\Desktop\misc\programacio\setuper\build\assets\frame0")


def relative_to_assets(path: str) -> Path:
    return ASSETS_PATH / Path(path)


window = Tk()

window.geometry("640x480")
window.configure(bg = "#C8EABC")


canvas = Canvas(
    window,
    bg = "#C8EABC",
    height = 480,
    width = 640,
    bd = 0,
    highlightthickness = 0,
    relief = "ridge"
)

canvas.place(x = 0, y = 0)
canvas.create_rectangle(
    0.0,
    131.0,
    104.0,
    469.0,
    fill="#C8EABC",
    outline="")

canvas.create_rectangle(
    0.0,
    0.0,
    640.0,
    118.0,
    fill="#B5E4FF",
    outline="")

canvas.create_text(
    167.0,
    13.0,
    anchor="nw",
    text="Welcome to Setuper",
    fill="#000000",
    font=("Inter", 32 * -1)
)

canvas.create_text(
    238.0,
    66.0,
    anchor="nw",
    text="Choose Folder",
    fill="#000000",
    font=("Inter", 24 * -1)
)

button_image_1 = PhotoImage(
    file=relative_to_assets("button_1.png"))
button_1 = Button(
    image=button_image_1,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_1 clicked"),
    relief="flat"
)
button_1.place(
    x=21.0,
    y=140.0,
    width=598.0,
    height=80.0
)

button_image_2 = PhotoImage(
    file=relative_to_assets("button_2.png"))
button_2 = Button(
    image=button_image_2,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_2 clicked"),
    relief="flat"
)
button_2.place(
    x=21.0,
    y=249.0,
    width=599.0,
    height=80.0
)

button_image_3 = PhotoImage(
    file=relative_to_assets("button_3.png"))
button_3 = Button(
    image=button_image_3,
    borderwidth=0,
    highlightthickness=0,
    command=lambda: print("button_3 clicked"),
    relief="flat"
)
button_3.place(
    x=21.0,
    y=367.0,
    width=599.0,
    height=80.0
)
window.resizable(False, False)
window.mainloop()
